"""Added hp.models.cascade

Revision ID: ba58b309b219
Revises: dca350e32f4a
Create Date: 2022-04-15 16:05:30.990726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba58b309b219'
down_revision = 'dca350e32f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.create_foreign_key(None, 'headphones', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'headphones', 'types', ['type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'headphones', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'headphones', 'colors', ['color_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.drop_constraint(None, 'headphones', type_='foreignkey')
    op.create_foreign_key(None, 'headphones', 'images', ['image_id'], ['id'])
    op.create_foreign_key(None, 'headphones', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'headphones', 'types', ['type_id'], ['id'])
    op.create_foreign_key(None, 'headphones', 'colors', ['color_id'], ['id'])
    # ### end Alembic commands ###
